# Generated by Django 4.2.10 on 2024-05-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='users.admin'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='users.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='placeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='users.place'),
        ),
    ]
