# Generated by Django 4.2.10 on 2024-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='datePost',
            field=models.DateTimeField(default=False),
        ),
    ]
