# Generated by Django 4.2.10 on 2024-05-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_isadmin_alter_post_datepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='users.user'),
        ),
    ]
